### ISSUE TITLE
October CMS 3.x compatibility

### ISSUE THREAD

**Issue by PubliAlex** [snipiba/oc-unique-media-finder-plugin#24]
Hello,

I really like your plugin, but unfortunately, as it's said on the plugin marketplace description page, it's not compatible with October CMS 3.x.

Now the 3.x is official, and default version to install for all new projects, do you have an estimate about when an update of this plugin will be compatible with 3.x ? 

Thank you

**Comment by snipiba** [comment]
> Hello,
> 
> I really like your plugin, but unfortunately, as it's said on the plugin marketplace description page, it's not compatible with October CMS 3.x.
> 
> Now the 3.x is official, and default version to install for all new projects, do you have an estimate about when an update of this plugin will be compatible with 3.x ?
> 
> Thank you

Done created a new plugin called Image Databanks seach inside october using code Snipi.MediaDatabanks

**Comment by PubliAlex** [comment]
It sound wonderful, I will thest this immediately !
